### ISSUE TITLE
Justified text

### ISSUE THREAD

**Issue by mulhoon** [namniak/CanvasTextWrapper#1]
Hi, great work. This looks very useful, well done.

Have you had any thoughts about justified text? There could be an option to flex the spaces between words or flex the space between letters so all lines match the same width.

**Comment by namniak** [comment]
hi. with the newer version 0.3.0 you can enable "justifyLines" option to stretch lines. Note that It flexes spaces between words (but not letters) which means single-word lines are not affected.
