### ISSUE TITLE
Possible to use with Plain HTML/JS

### ISSUE THREAD

**Issue by aakey7** [namniak/CanvasTextWrapper#31]
Is it possible to just include the .js as a script in an html file?

I have tried this but get the following error:

```
Cannot read property 'hasOwnProperty' of undefined
    at CanvasTextWrapper
```

**Comment by namniak** [comment]
It should be working ok with both browserify and html include. 
this example site is simply including it in html 
head http://namniak.github.io/canvas-text-wrapper/ and it is available as global/window function
https://github.com/namniak/canvas-text-wrapper/blob/gh-pages/index.html#L8
