### ISSUE TITLE
Allow new lines

### ISSUE THREAD

**Issue by cavill** [namniak/CanvasTextWrapper#4]
Is there some workaround to allow blank lines in the rendered text? So if the text is derived from a textarea, the user could write over multiple lines, but with a break where required.

Either way, thank you for your work on this.

**Comment by namniak** [comment]
hi. I updated the library and with version 0.3.0 text can break on every new line character '\n'. This is controlled by "allowNewLine" property which is enabled by default. So you can get multiline text from textarea or control where your text breaks. Note it' will not allow blank lines.
