### ISSUE TITLE
consider not making CanvasTextWrapper a constructor

### ISSUE THREAD

**Issue by nickdesaulniers** [namniak/CanvasTextWrapper#9]
it looks like the prototype simply has helper functions used at creation, not methods meant to be used.  Consider making CanvasTextWrapper simply a function as opposed to a constructor fn.  CanvasTextWrappers are not reusable (you construct them once, then never use them again), so it's kind of odd to have to construct them.

**Comment by namniak** [comment]
Fair enough. Will do some re-factoring soon. Thanks.
